name: ci
on:
  - push
  - pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: "15"

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
          restore-keys: ${{ runner.os }}-

      - name: Build
        uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.18.7
          run_install: true

      - name: Release
        if: github.event_name == 'push'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
